version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:latest
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - "/app/node_modules" # just leave folder as is in the container
      - "./server:/app" # map the local folder to the container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      # name of service "postgres" is the hostname
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
