name: Deploy MultiDocker
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Test Client
              run: |
                  docker build -t cswitzer/react-test -f ./client/Dockerfile.dev ./client
                  docker run -e CI=true cswitzer/react-test npm test

            - name: Build Client Image
              run: docker build -t cswitzer/multi-client ./client

            - name: Build Nginx Image
              run: docker build -t cswitzer/multi-nginx ./nginx

            - name: Build Server Image
              run: docker build -t cswitzer/multi-server ./server

            - name: Build Worker Image
              run: docker build -t cswitzer/multi-worker ./worker

            - name: Push Images
              run: |
                  docker push cswitzer/multi-client
                  docker push cswitzer/multi-nginx
                  docker push cswitzer/multi-server
                  docker push cswitzer/multi-worker
